language: python
dist: trusty
python:
  - 2.7
  - 3.4
  - 3.5
notifications:
  email: false
addons:
  apt:
    packages:
        - libblas-dev
        - liblapack-dev
env:
    global:
        # Maximal dependencies
        - DEPENDS="cython numpy scipy matplotlib"
matrix:
  include:
    - python: 3.5
      env:
        - RUN_R_TESTS=1
    - python: 2.7
      env:
        - RUN_R_TESTS=1
    # Testing without matplotlib
    - python: 2.7
      env:
        - DEPENDS="cython numpy scipy"
    # Documentation doctests
    - python: 2.7
      env:
        - DOC_DOC_TEST=1
    # Setup.py install
    - python: 2.7
      env:
        - INSTALL_TYPE=setup
    - python: 2.7
      env:
        # Sdist install should collect all dependencies
        - INSTALL_TYPE=sdist
        - DEPENDS=
    - python: 2.7
      env:
        # Wheel install should collect all dependencies
        - INSTALL_TYPE=wheel
        - DEPENDS=
    - python: 2.7
      env:
        - INSTALL_TYPE=requirements
        - DEPENDS=
install:
  - pip install -r requirements.txt;
  - python -c "from statsmodels.api import PHReg"

script:
    - pip install nose
